# Generated by Django 5.0.2 on 2025-02-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_proyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
